lib/kbuudl_web/router.ex
defmodule KbuudlWeb.Router do
  use KbuudlWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Kbuudl.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KbuudlWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", KbuudlWeb do
  #   pipe_through :api
  # end
end

lib/kbuudl/accounts.ex
defmodule Kbuudl.Accounts do
  @moduledoc """
  The Accounts context.
  """

  import Ecto.Query, warn: false
  alias Kbuudl.Repo
  alias Kbuudl.Accounts.User
  alias Kbuudl.Accounts.Credential

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  def change_registration(%User{} = user, params) do
    User.registration_changeset(user, params)
  end

  def register_user(attrs \\ %{}) do
    %User{}
    |> User.registration_changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Returns the list of credentials.

  ## Examples

      iex> list_credentials()
      [%Credential{}, ...]

  """
  def list_credentials do
    Repo.all(Credential)
  end

  @doc """
  Gets a single credential.

  Raises `Ecto.NoResultsError` if the Credential does not exist.

  ## Examples

      iex> get_credential!(123)
      %Credential{}

      iex> get_credential!(456)
      ** (Ecto.NoResultsError)

  """
  def get_credential!(id), do: Repo.get!(Credential, id)

  @doc """
  Updates a credential.

  ## Examples

      iex> update_credential(credential, %{field: new_value})
      {:ok, %Credential{}}

      iex> update_credential(credential, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_credential(%Credential{} = credential, attrs) do
    credential
    |> Credential.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Credential.

  ## Examples

      iex> delete_credential(credential)
      {:ok, %Credential{}}

      iex> delete_credential(credential)
      {:error, %Ecto.Changeset{}}

  """
  def delete_credential(%Credential{} = credential) do
    Repo.delete(credential)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking credential changes.

  ## Examples

      iex> change_credential(credential)
      %Ecto.Changeset{source: %Credential{}}

  """
  def change_credential(%Credential{} = credential) do
    Credential.changeset(credential, %{})
  end
end

lib/kbuudl/accounts/credential.ex
defmodule Kbuudl.Accounts.Credential do
  use Ecto.Schema
  import Ecto.Changeset

  schema "credentials" do
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    belongs_to :user, Kbuudl.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(credential, attrs) do
    credential
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
    |> validate_length(:password, min: 6, max: 100)
    |> unique_constraint(:email)
    |> put_pass_hash()
  end

  defp put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, Argon2.add_hash(password))
  end
  defp put_pass_hash(changeset), do: changeset
end

lib/kbuudl/accounts/user.ex
defmodule Kbuudl.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Kbuudl.Accounts.Credential

  schema "users" do
    field :name, :string
    field :username, :string
    has_one :credential, Credential

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username])
    |> validate_required([:name, :username])
    |> validate_length(:username, min: 1, max: 20)
  end

  def registration_changeset(user, params) do
    user
    |> changeset(params)
    |> cast_assoc(:credential, with: &Credential.changeset/2, required: true)
  end
end

lib/kbuudl/application.ex
defmodule Kbuudl.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Kbuudl.Repo,
      # Start the endpoint when the application starts
      KbuudlWeb.Endpoint
      # Starts a worker by calling: Kbuudl.Worker.start_link(arg)
      # {Kbuudl.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Kbuudl.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    KbuudlWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/kbuudl/repo.ex
defmodule Kbuudl.Repo do
  use Ecto.Repo,
    otp_app: :kbuudl,
    adapter: Ecto.Adapters.Postgres
end

lib/kbuudl_web/controllers/page_controller.ex
defmodule KbuudlWeb.PageController do
  use KbuudlWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/kbuudl_web/controllers/user_controller.ex
defmodule KbuudlWeb.UserController do
  use KbuudlWeb, :controller

  alias Kbuudl.Accounts
  alias Kbuudl.Accounts.User

  plug :authenticate_user when action in [:show]

  def new(conn, _params) do
    changeset = Accounts.change_registration(%User{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "#{user.name} created.")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

end

lib/kbuudl_web/views/error_view.ex
defmodule KbuudlWeb.ErrorView do
  use KbuudlWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/kbuudl_web/views/layout_view.ex
defmodule KbuudlWeb.LayoutView do
  use KbuudlWeb, :view
end

lib/kbuudl_web/views/page_view.ex
defmodule KbuudlWeb.PageView do
  use KbuudlWeb, :view
end

lib/kbuudl_web/views/user_view.ex
defmodule KbuudlWeb.UserView do
  use KbuudlWeb, :view
end

lib/kbuudl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Kbuudl · Your Collection</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav class="amber darken-4" role="navigation">
      <div class="nav-wrapper container">
        <%= link "Kbuudl", to: Routes.page_path(@conn, :index), id: "logo-container", class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
        </ul>
        <ul id="nav-mobile" class="sidenav">
          <li><a href="#">Navbar Link</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav>

    <div class="section no-pad-bot">
      <div role="main" class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <footer class="page-footer orange">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Company Bio</h5>
            <p class="grey-text text-lighten-4">Nulla mauris quam, aliquet in fringilla et, aliquet in nisl. Etiam finibus non felis vel dapibus. Quisque cursus porttitor nibh gravida vulputate. Sed a leo augue. Proin a velit a mauris venenatis faucibus.</p>


          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Settings</h5>
            <ul>
              <li><a class="white-text" href="#!">Link 1</a></li>
              <li><a class="white-text" href="#!">Link 2</a></li>
              <li><a class="white-text" href="#!">Link 3</a></li>
              <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Connect</h5>
            <ul>
              <li><a class="white-text" href="#!">Link 1</a></li>
              <li><a class="white-text" href="#!">Link 2</a></li>
              <li><a class="white-text" href="#!">Link 3</a></li>
              <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        Made by the Preston Group, LLC.
        </div>
      </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/kbuudl_web/templates/page/index.html.eex
<section class="kbdl-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Kbuudl" %></h1>
  <p>A productive way to store your collectables.</p>
</section>

<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Cool ways to store stuff</h5>

          <p class="light">Vivamus finibus turpis id nunc ornare, at facilisis enim luctus. Morbi ornare cursus fringilla. Aenean eleifend elementum nibh sit amet placerat. Etiam sapien neque, posuere lobortis vehicula non, porttitor a magna.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">Great experiences</h5>

          <p class="light">Sed vitae tempus risus. Vestibulum vitae dolor eu odio pellentesque varius. Donec luctus eget arcu eget sagittis. Phasellus rutrum iaculis massa, ac ultrices urna mollis at. Sed dapibus ligula id vehicula placerat. Vestibulum laoreet felis elit, ut scelerisque urna fringilla vel.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Inexpensive to keep collectables.</h5>

          <p class="light">Aenean eget nibh eget justo porttitor sodales sit amet ac nunc. Ut sit amet congue lacus. Praesent finibus lectus vulputate libero scelerisque, non bibendum elit mollis. </p>
        </div>
      </div>
    </div>

  </div>
  <br><br>
</div>

lib/kbuudl_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/kbuudl_web/templates/user/form.html.eex
<div class="container">
  <div class="row">
    <%= form_for @changeset, @action, [class: "col s12"], fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="row">
        <div class="input-field col s12">
          <%= label f, :name %>
          <%= text_input f, :name %>
          <%= error_tag f, :name %>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= label f, :username %>
          <%= text_input f, :username %>
          <%= error_tag f, :username %>
        </div>
      </div>

      <%= inputs_for f, :credential, fn cf -> %>
        <div class="row">
          <div class="input-field col s12">
            <%= label cf, :email %>
            <%= text_input cf, :email %>
            <%= error_tag cf, :email %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= label cf, :password %>
            <%= password_input cf, :password %>
            <%= error_tag cf, :password %>
          </div>
        </div
      <% end %>


      <div>
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    <% end %>
  </div>
</div>

lib/kbuudl_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/kbuudl_web/templates/user/new.html.eex
<div class="section">

  <h1>Registration</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

</div>

lib/kbuudl_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

</ul>